### ISSUE TITLE
Use JSON file to edit the contents of the portfolio

### ISSUE THREAD

**Issue by diogo405** [BraydenTW/react-tailwind-portfolio#1]
Hey mate, what you think about having a JSON as an input to generate the portfolio? That way anyone could have their own folio only changing the file.

**Comment by BraydenTW** [comment]
Good idea. I'll see if I can implement these changes today. 

Thanks for the suggestion!

**Comment by shishirtiwari23** [comment]
@BraydenTW  I Have fixed This Issue too ,and Will Make a PR if assigned
