### ISSUE TITLE
The data should be passed through props instead of hard coding 

### ISSUE THREAD

**Issue by shishirtiwari23** [BraydenTW/react-tailwind-portfolio#3]
I went through the repository and i found out that in order to use this portfolio template you need to hard code the data and i don't think that is the right way of using the data ,the data should be passed through props and props may collect that data through a JSON file as mentioned in #1

**Comment by shishirtiwari23** [comment]
@BraydenTW I already fixed this issue and will make a PR if assigned !

**Comment by BraydenTW** [comment]
Sounds good! Thanks!
