### ISSUE TITLE
Hacktoberfest contribution

### ISSUE THREAD

**Issue by naveennamani** [BraydenTW/react-tailwind-portfolio#6]
Is this repository accepting hacktoberfest contribution and is it active?
I wanted to contribute by making a small enhancement to showcase the projects. If @BraydenTW can respond in time, I'll start working on the feature.

Thanks.

**Comment by BraydenTW** [comment]
Yes @naveennamani, we are!

Feel free to submit a PR when you are ready.

**Comment by naveennamani** [comment]
Hey @BraydenTW , I made my PR #7, have a look at it, I made it very quick, so if you feel any improvements are needed, we can elaborate and work on it.
Thanks.

**Comment by naveennamani** [comment]
Hi @BraydenTW, I'm closing this issue, thanks for allowing me to contribute. If you want to add any feature or wants to improve my PR, please you can comment on this issue.
